version: "3.8"

services:
  web:
    build: .
    container_name: web
    command: php artisan serve --host=0.0.0.0 --port=8000
    env_file: .env
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - redis
    networks:
      - swstarter

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - swstarter

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ./docker/data/redis:/data
    ports:
      - 6379:6379
    networks:
      - swstarter

networks:
  swstarter:
